#!/usr/bin/env bash
# Render CV YAML to public/resume.pdf and content/resume.md (RenderCV CLI).
# Optional: CV_PHONE="+14155551234" (E.164) to include a phone in the PDF
# without committing it (see cv/david_marr_rendercv.yaml).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
if ! python3 -c "import rendercv" 2>/dev/null; then
  echo "rendercv not found; installing from requirements-cv.txt" >&2
  python3 -m pip install -r "$ROOT/requirements-cv.txt"
fi

GEN="$(mktemp)"
trap 'rm -f "$GEN"' EXIT

RENDERCV_EXTRA=()
if [ -n "${CV_PHONE:-}" ]; then
  RENDERCV_EXTRA+=(--cv.phone "$CV_PHONE")
fi

python3 -m rendercv render "$ROOT/cv/david_marr_rendercv.yaml" \
  -o "$ROOT/.rendercv-output" \
  -pdf ../public/resume.pdf \
  -md "$GEN" \
  -nohtml -nopng \
  -q \
  "${RENDERCV_EXTRA[@]}"

{
  cat <<'EOF'
---
title: Résumé
description: CV for David Marr — engineering leader, open source, and climate tech.
seo:
  title: Résumé | David Marr
  description: Engineering leader with 25 years building production software.
---

<!-- Generated by scripts/render-cv.sh from cv/david_marr_rendercv.yaml. Edit the YAML, not this file. -->

Also available as [**PDF**](/resume.pdf).

EOF
  cat "$GEN"
} > "$ROOT/content/resume.md"
