#!/usr/bin/env bash
# Render CV YAML to public/resume.pdf, public/resume-ats.pdf, and content/resume.md.
# Optional: CV_PHONE="+14155551234" (E.164) to include a phone in the PDF
# without committing it (see cv/david_marr_rendercv.yaml).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
if ! python3 -c "import rendercv" 2>/dev/null; then
  echo "rendercv not found; installing from requirements-cv.txt" >&2
  python3 -m pip install -r "$ROOT/requirements-cv.txt"
fi

GEN="$(mktemp)"
GEN_ATS="$(mktemp)"
trap 'rm -f "$GEN" "$GEN_ATS"' EXIT

# Build argv in one array so `set -u` never expands an empty/unset optional array
# (some Bash versions error on "${optional[@]}" when optional was never appended to).
cmd=(
  python3 -m rendercv render "$ROOT/cv/david_marr_rendercv.yaml"
  -o "$ROOT/.rendercv-output"
  -pdf ../public/resume.pdf
  -md "$GEN"
  -nohtml -nopng
  -q
)
if [ -n "${CV_PHONE:-}" ]; then
  cmd+=(--cv.phone "$CV_PHONE")
fi
"${cmd[@]}"

# ATS-friendly PDF variant: plain contact line (no icon glyphs) for parsers.
cmd_ats=(
  python3 -m rendercv render "$ROOT/cv/david_marr_rendercv.yaml"
  -o "$ROOT/.rendercv-output"
  -pdf ../public/resume-ats.pdf
  -md "$GEN_ATS"
  -nohtml -nopng
  -q
  --design.header.connections.show_icons false
  --design.header.connections.separator " | "
)
if [ -n "${CV_PHONE:-}" ]; then
  cmd_ats+=(--cv.phone "$CV_PHONE")
fi
"${cmd_ats[@]}"

python3 "$ROOT/scripts/harmonize_resume_headings.py" < "$GEN" > "${GEN}.harmonized"
mv "${GEN}.harmonized" "$GEN"

{
  cat <<'EOF'
---
title: Résumé
description: CV for David Marr — engineering leader, open source, and climate tech.
seo:
  title: Résumé | David Marr
  description: Engineering leader with 25 years building production software.
---

<!-- Generated by scripts/render-cv.sh from cv/david_marr_rendercv.yaml (headings harmonized for web: one h1, section h2, role h3). Edit the YAML, not this file. -->

Also available as [**PDF**](/resume.pdf){external}.

EOF
  cat "$GEN"
} > "$ROOT/content/resume.md"
